{
 "title": "Inbound media details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "clusterChosen", "label": "System ID", "query": { "query": "label_values(cluster)" } },
   { "name": "camNamePrefix", "label": "Camera name prefix", "query": { "query": "label_values(object)" } }
  ]
 },
 "panels": [
  {
   "title": "Offline streams (non dynamic or requested dynamic)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vnx_rtsp_connection_errors_in_a_row{cluster=~\"$clusterChosen\"}>0) or vector(0)",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Offline streams (non dynamic or requested dynamic)",
   "type": "table",
   "description": "Number of RTSP connection errors in a row",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "vnx_rtsp_connection_errors_in_a_row{cluster=~\"$clusterChosen\"}>0",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Video data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(vnx_media_stream_bytes_total {media_type=\"video\", cluster=~\"$clusterChosen\", object =~ \".*$camNamePrefix.*\"})",
     "legendFormat": "{{object}} @ {{cluster}}"
    }
   ]
  },
  {
   "title": "RTP packet loss rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (object) (rate(vnx_rtsp_rtp_packets_lost{cluster=~\"$clusterChosen\", object =~ \".*$camNamePrefix.*\"}))",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Video sample rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    {
     "expr": "rate(vnx_media_stream_samples_total {media_type=\"video\", cluster=~\"$clusterChosen\", object =~ \".*$camNamePrefix.*\"})",
     "legendFormat": "{{object}}"
    }
   ]
  },
  { "title": "RTP transport details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Media sample period - presentation",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(vnx_media_stream_sample_period_pts_bucket{cluster=~\"$clusterChosen\", object =~ \".*$camNamePrefix.*\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media sample period - acquisition",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(vnx_media_stream_sample_period_rtc_bucket{cluster=~\"$clusterChosen\", object =~ \".*$camNamePrefix.*\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media sample size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(vnx_media_stream_sample_size_bucket{cluster=~\"$clusterChosen\", object =~ \".*$camNamePrefix.*\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTP packets loss rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(vnx_rtsp_rtp_packets_lost{cluster=~\"$clusterChosen\", media_type=\"video\", object =~ \".*$camNamePrefix.*\"})",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "RTP sample loss rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(vnx_rtsp_rtp_samples_lost{cluster=~\"$clusterChosen\", media_type=\"video\", object =~ \".*$camNamePrefix.*\"})",
     "legendFormat": "{{object}}"
    }
   ]
  }
 ]
}