{
 "title": "Inbound video stats",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "clusterChosen", "label": "Cluster ID", "query": { "query": "label_values(cluster)" } },
   { "name": "camNamePrefix", "label": "Camera name prefix", "query": { "query": "label_values(object)" } }
  ]
 },
 "panels": [
  {
   "title": "Total inbound media sample rate per cluster (all cameras)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(vnx_media_stream_samples_total {media_type=\"video\", cluster=~\"$clusterChosen\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total inbound data rate per cluster (all cameras)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(vnx_media_stream_bytes_total {media_type=\"video\", cluster=~\"$clusterChosen\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound sample rate per camera",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(vnx_media_stream_samples_total {media_type=\"video\", cluster=~\"$clusterChosen\", object=~\".*$camNamePrefix.*\"})",
     "legendFormat": "{{object}} @ {{cluster}}"
    }
   ]
  },
  {
   "title": "Inbound video data rate per camera",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(vnx_media_stream_bytes_total {media_type=\"video\", cluster=~\"$clusterChosen\", object=~\".*$camNamePrefix.*\"})",
     "legendFormat": "{{object}} @ {{cluster}}"
    }
   ]
  },
  {
   "title": "Total media data received over time interval",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (object, cluster) (increase(vnx_media_stream_bytes_total {cluster=~\"$clusterChosen\", object=~\".*$camNamePrefix.*\"}[$__range]))",
     "legendFormat": "{{object}} @ {{cluster}}"
    }
   ]
  }
 ]
}