{
 "title": "Storage and streaming",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "clusterChosen", "label": "System ID", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Media storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Space used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vnx_storage_space_used{cluster=~\"$clusterChosen\"}",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Free space left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vnx_storage_volume_space_free{cluster=~\"$clusterChosen\"}",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Overall archive depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vnx_storage_timestamp_newest{cluster=~\"$clusterChosen\"}-vnx_storage_timestamp_oldest{cluster=~\"$clusterChosen\"}\r\n",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Obsolescence",
   "type": "timeseries",
   "description": "How long ago the most recent media data has been written to media storage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "timestamp(vnx_storage_timestamp_newest{cluster=~\"$clusterChosen\"})*1000-vnx_storage_timestamp_newest{cluster=~\"$clusterChosen\"}",
     "legendFormat": "{{object}}"
    }
   ]
  },
  { "title": "Streaming server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Outbound streaming data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(vnx_streaming_server_bytes_total{cluster=~\"$clusterChosen\"}[1m])",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Outbound streaming sample rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(vnx_streaming_server_samples_total{cluster=~\"$clusterChosen\"}[1m])",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "New sessions per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(vnx_streaming_server_sessions_total{cluster=~\"$clusterChosen\"}[1m])*60",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Streaming server sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vnx_streaming_server_sessions{cluster=~\"$clusterChosen\", object=~\"rtspsrv.*\"}",
     "legendFormat": "{{object}}"
    },
    {
     "expr": "vnx_streaming_server_sessions{cluster=~\"$clusterChosen\", object=~\"webrtc.*\"}",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "RTCP reports received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(vnx_streaming_server_rtcp_reports_total{cluster=~\"$clusterChosen\"}[1m])",
     "legendFormat": "RRs for {{object}}"
    },
    {
     "expr": "rate(vnx_streaming_server_rtcp_reported_lost_total{cluster=~\"$clusterChosen\"}[1m])",
     "legendFormat": "Picture lost reports for {{object}}"
    }
   ]
  }
 ]
}